import { Geist, Geist_Mono, Sigmar, Audiowide, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sigmar = Sigmar({
  variable: "--font-sigmar",
  subsets: ["latin"],
  weight: ["400"]
})

const roboto = Roboto({
  variable: "--font-robo",
  weight: ["400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sigmar.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
